src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CoursRepository::class)
 */
class Cours
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_ajout;

    /**
     * @ORM\Column(type="boolean")
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="cours")
     */
    private $categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateAjout(): ?bool
    {
        return $this->date_ajout;
    }

    public function setDateAjout(bool $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/CoursType.php
<?php

namespace App\Form;

use App\Entity\Cours;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('etat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Cours::class,
        ]);
    }
}

src/Controller/CoursController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Form\CoursType;
use App\Repository\CoursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/cours")
 */
class CoursController extends AbstractController
{
    /**
     * @Route("/", name="cours_index", methods={"GET"})
     */
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('cours/index.html.twig', [
            'cours' => $coursRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="cours_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $cour = new Cours();
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($cour);
            $entityManager->flush();

            return $this->redirectToRoute('cours_index');
        }

        return $this->render('cours/new.html.twig', [
            'cour' => $cour,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cours_show", methods={"GET"})
     */
    public function show(Cours $cour): Response
    {
        return $this->render('cours/show.html.twig', [
            'cour' => $cour,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="cours_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Cours $cour): Response
    {
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('cours_index');
        }

        return $this->render('cours/edit.html.twig', [
            'cour' => $cour,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cours_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Cours $cour): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cour->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($cour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('cours_index');
    }
}

templates/cours/_delete_form.html.twig
<form method="post" action="{{ path('cours_delete', {'id': cour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cours/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cours{% endblock %}

{% block body %}
    <h1>Edit Cours</h1>

    {{ include('cours/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('cours_index') }}">back to list</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}

templates/cours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours index{% endblock %}

{% block body %}
    <h1>Cours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Date_ajout</th>
                <th>Etat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cour in cours %}
            <tr>
                <td>{{ cour.id }}</td>
                <td>{{ cour.nom }}</td>
                <td>{{ cour.dateAjout ? cour.dateAjout|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ cour.etat ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('cours_show', {'id': cour.id}) }}">show</a>
                    <a href="{{ path('cours_edit', {'id': cour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('cours_new') }}">Create new</a>
{% endblock %}

templates/cours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cours{% endblock %}

{% block body %}
    <h1>Create new Cours</h1>

    {{ include('cours/_form.html.twig') }}

    <a href="{{ path('cours_index') }}">back to list</a>
{% endblock %}

templates/cours/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours{% endblock %}

{% block body %}
    <h1>Cours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cour.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ cour.nom }}</td>
            </tr>
            <tr>
                <th>Date_ajout</th>
                <td>{{ cour.dateAjout ? cour.dateAjout|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ cour.etat ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('cours_index') }}">back to list</a>

    <a href="{{ path('cours_edit', {'id': cour.id}) }}">edit</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}